server:
  port: 80
  servlet :
    context-path : /
    encoding:
      enabled: true
      force : true
      charset: UTF-8

# spring 설정
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/ #파일의 시작위치
    suffix: .html #파일의 확장자명
    cache: false #캐시 저장 여부
    check-template-location: true #파일의 존재 여부 확인
    mode : HTML5
  mvc:
    static-path-pattern: "/static/**" #정적 파일 경로 지정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    driver-class-name: oracle.jdbc.OracleDriver
    username : C##GORILLACMAP
    password: 5105

#mybatis 설정
mybatis:
  type-aliases-package: com.gorilla.camp.gorillacamp.*.vo
  mapper-locations: mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
